#!/bin/bash

set -e

echo "Running commit-msg hook"

if [ -z "$1" ]; then
    echo "Error: Missing commit message title."
    exit 1
fi

commitTitle="$(cat $1 | head -n1)"

if echo "$commitTitle" | grep -q "Merge branch"; then
    echo "Ignoring merge branch commit title and continuing commit."
    exit 0
fi

if echo "$commitTitle" | grep -q "Revert"; then
    echo "Ignoring revert commit title and continuing commit."
    exit 0
fi

if echo "$commitTitle" | grep -q "cherry pick"; then
    echo "Ignoring cherry pick commit title and continuing commit."
    exit 0
fi

if ! echo "$commitTitle" | grep -qE '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore)'; then
    echo "Error: Commit title does not follow required format."
    echo "See documentation below for guidance:"
    echo "https://kapeli.com/cheat_sheets/Conventional_Commits.docset/Contents/Resources/Documents/index"
    exit 1
fi
